version: '3'

services:
  redis:
    image: redis
    ports:
     - "6379:6379"
    network_mode: "host"
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    network_mode: "host"
  server:
    build:
      context: .
      dockerfile: DockerfileDeploy
    ports:
     - "8080:8080"
    volumes:
     - "/var/log:/var/log"
    network_mode: "host"
    depends_on:
     - redis
     - mongo
